class PracticeFormPageLocators:
    FIRST_NAME_INPUT_FIELD = '#firstName'
    LAST_NAME_INPUT_FIELD = '#lastName'
    MOBILE_NUMBER_INPUT_FIELD = '#userNumber'
    GENDER_RADIO_BUTTONS = '.custom-radio.custom-control'
    SUBMIT_BUTTON = '#submit'
    THANKS_FOR_SUBMITTING_HEADER = '#example-modal-sizes-title-lg'
    UPLOAD_FILE_BUTTON = '#uploadPicture'
    STUDENT_NAME_TABLE_CELL_VALUE = '.table tr:nth-of-type(1) td:nth-of-type(2)'
    MOBILE_NUMBER_TABLE_CELL_VALUE = '.table tr:nth-of-type(4) td:nth-of-type(2)'
    GENDER_TABLE_CELL_VALUE = '.table tr:nth-of-type(3) td:nth-of-type(2)'
    PICTURE_NAME_TABLE_CELL_VALUE = '.table tr:nth-of-type(8) td:nth-of-type(2)'
    CLOSE_SUMMARY_MODAL_BUTTON = '#closeLargeModal'